fix(bug): links fields broken #11
schmelto/LinkFree_generator pull request #19
Opened 2022-06-11 19:00 UTC by darkterminal

Fix links section table fields broken

2022-06-11 20:58 UTC, emmalearnscode requested changes
Overall this looks good but there are a few improvements that can be made.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-11 20:58 UTC, emmalearnscode commented on index.html
> +                <td><buntton class="btn btn-sm btn-danger ibtnDel">Delete</buntton></td>
There appears to be a typo in the button tag
```suggestion
                <td><button class="btn btn-sm btn-danger ibtnDel">Delete</button></td>
```

and it should also have type="button" because it is not a submit button

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-11 20:58 UTC, emmalearnscode commented on index.html
> +                    <input type="text" class="form-control" placeholder="Text Link" name="name${counter}" required/>
I think the placeholder text was clearer before when it matched the labels. Text link is confusing to me when the label says name.

2022-06-11 20:58 UTC, emmalearnscode commented on index.html
> +                    <input type="text" name="icon${counter}" class="form-control" placeholder="icon" />
There is some inconsistency with placeholder text and capitalization. Either all placeholders should start with a capital or none of them should.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-12 14:43 UTC, schmelto commented
I'm currently on vacation but hopefully I will find time tomorrow to review.

2022-06-13 11:37 UTC, schmelto commented on index.html
> +                    <input type="text" class="form-control" placeholder="Text Link" name="name${counter}" required/>
```suggestion
                    <input type="text" class="form-control" placeholder="name" name="name${counter}" required/>
```

2022-06-13 11:37 UTC, schmelto commented on index.html
> +                    <input type="text" class="form-control" placeholder="Link URL" name="url${counter}" required/>
```suggestion
                    <input type="text" class="form-control" placeholder="url" name="url${counter}" required/>
```

2022-06-13 11:37 UTC, schmelto approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-06-13 11:38 UTC, merged